org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=false
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
# Increase connection timeout to prevent "Read timed out"
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

org.gradle.offline=true

# Disable CMake features as it triggers download failures
android.defaults.buildfeatures.cmake=false
android.enableCMakeAppBundle=false
flutter.native-assets=false
